// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xmvpkuxanuobxppyyarc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhtdnBrdXhhbnVvYnhwcHl5YXJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxMjA3MzksImV4cCI6MjA2MDY5NjczOX0.9pxxw02LLpq8c-rfRJqpU1ZGBAS3DzMEN_iu_V7T_zg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);